language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.2
  - ruby-head
  - jruby-9.0.3.0
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby-9.0.3.0
  fast_finish: true
before_install: gem install bundler -v 1.11.2
